name: Auto apply labels to pull requests

on:
  pull_request:
    branches:
      - main
      
jobs:
  add-label:
    name: Add labels
    runs-on: ubuntu-latest
    steps:
    - name: PR Labeler
      # You may pin to the exact commit or the version.
      # uses: TimonVS/pr-labeler-action@8b99f404a073744885d8021d1de4e40c6eaf38e2
      uses: TimonVS/pr-labeler-action@v4.1.1
      with:
        configuration-path: .github/pr-drafter.yml
